#include "stm32f4xx_hal.h"
#include "sht31.h"

/*
 * NOTE:
 * Ensure that the following functions are defined elsewhere in your project,
 * typically generated by STM32CubeMX:
 *   - SystemClock_Config()
 *   - MX_GPIO_Init()
 *   - MX_I2C1_Init()
 * Also declare the I2C handle used for the sensor.
 */
extern I2C_HandleTypeDef hi2c1;

SHT31_HandleTypeDef sht31;
float temperature;
float humidity;

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();

    /* Initialize SHT31 sensor at default I2C address 0x44 */
    SHT31_Init(&sht31, &hi2c1, 0x44);

    while (1)
    {
        if (SHT31_ReadTempHum(&sht31, &temperature, &humidity) == HAL_OK)
        {
            /* Values are now stored in temperature and humidity variables */
            /* You can transmit them via UART, log them, update a display, etc. */
        }
        HAL_Delay(1000);
    }
}
